### PR TITLE
Refactor lighting section

### PR DESCRIPTION
**Pull request by donutcrab**
- lighting settings selection on top
- button creation with v-for
- colorpicker refactoring
- updated file structure

I plan on further refining the components
If a change is not desired, let me know

### CODE REVIEW

**Comment by FrostyCoolSlug** [comment]
Most of this is looking great, thanks, just a couple of points above that need addressing, but otherwise good.

I'm honestly not sure how I feel about the Lighting buttons at the top, in the official app there's a lot of 'dead space' placed above and below the tab content so that everything is properly aligned between tab switches.

With this change to have the buttons at the top, there's suddenly a huge vertical size jump that exists only on that tab, which looks a little jaring when moving between things.

At the same time, the buttons at the top make *FAR* more sense than the buttons I had previously on the side, so I'm happy to pull that, but it's something that may need a closer look.

**Comment by donutcrab** [comment]
I fully agree with you on the hight difference, opens the question on how close we want to resemble the original app.

**Comment by donutcrab** [comment]
And I currently cant see any review comments :disappointed: 
Is this a permissions issue?

**Comment by FrostyCoolSlug** [comment]
I'm not entirely sure, first time running a review here, I'll need to do some reading. As for the comments:

`LightingTab.vue` line 41, the `<style>` tag needs to be `<style scoped>`, as it's affecting anything that has a `.button` class (including profile buttons), leading to some weirdness:
image

`LightingTab.vue` line 23 doesn't work. `isDeviceMini` is a dynamic property which can change during runtime, so the values need to be wrapped in a proxy method that monitors for those changes. On the first run, isDeviceMini will always return true until the code has found a device and loaded up the UI.

**Comment by donutcrab** [comment]
isn't the isDeviceMini() from util already a function with this exact purpose?

**Comment by FrostyCoolSlug** [comment]
> I fully agree with you on the hight difference, opens the question on how close we want to resemble the original app.

I'm honestly not massively committed to keeping them identical anymore, when I first wrote this it was mostly a rush job to try and keep in line with the daemon, it made sense to use the design of the original to aid migration from windows (a familiar interface), and so that I didn't have to come up with a new interface as I was going.

With that said, things have slowly been drifting away, the profile section has seen some changes in the name of accessibility, and I'm fine with other things changing as well.

**Comment by FrostyCoolSlug** [comment]
> isn't the isDeviceMini() from util already a function with this exact purpose?

It is, when it's bound to a component (via v-if, or some other method), Vue maintains a proxy to the underlying store value, so if the return value of isDeviceMini changes due to a backing store change, it'll update the component dynamically.

If there is no active device in the backing store, isDeviceMini will return true regardless. Due to the way the page loads, and how the device store is populated, the first call when building the page won't have a device set (this will also be the case if a user has multiple devices, and is viewing the 'Select a Device' page).
Because of the way you're handling the tab presentation, that proxy isn't established, and you'll only recieve the value at time of call, and not be notified if that value changes during runtime.

**Comment by FrostyCoolSlug** [comment]
Just checked your latest commit, that's fixed it :)

**Comment by FrostyCoolSlug** [comment]
Last request, for the input boxes in the Colour pickers, can you text-align: center them? They look a little odd slightly off to the left :)

**Comment by FrostyCoolSlug** [comment]
Perfect, I'll merge that in, and it'll be included in 0.9.0.

Thanks!

**Pull request merged**
