### PR TITLE
started refactoring

### PR DESCRIPTION
**Pull request by donutcrab**
composition structure for the lighting settings
File structure is not finalised
please let me know if these changes lead in the desired direction

### CODE REVIEW

**Comment by FrostyCoolSlug** [comment]
Looking much better than it was. The only consideration at the moment is that some of the button lists should probably be radio lists to aid in accessibility. I've been slowly making this change in various places (Faders.vue is a good example) where it uses a role="radiogroup" and the RadioItem buttons.

The main reason is that a radio button list is clearer in indicating to screen readers and visually impaired users that only one item can be selected at a time, where as the historical buttons imply otherwise. 

Other than that, loving the direction :)

**Comment by donutcrab** [comment]
added role="radiogroup" to container
added type="radio" to button

is this what you meant?

**Comment by FrostyCoolSlug** [comment]
As context, the Radio implementation is available at:
https://github.com/GoXLR-on-Linux/goxlr-ui/blob/main/src/components/button_list/RadioItem.vue

And an example of a button list implementing them:
https://github.com/GoXLR-on-Linux/goxlr-ui/blob/main/src/components/sections/Faders.vue

**Comment by FrostyCoolSlug** [comment]
Looking good, the only comment is that the group= parameter needs to be unique across all radio groups (I see the group 'Button' defined twice), it also, oddly, doesn't need to be human readable, it's just a general group identifier, so something like (for example) `lighting_cough_buttons` would be generally acceptable.

Otherwise, it's looking great. I'm taking a couple of days off general work on the util, but will keep an eye on this PR, feel free to continue down this path, and let me know when you're in a position that everything is ready for a merge :)

Thanks!

**Comment by FrostyCoolSlug** [comment]
Code looks good so I'll accept this as-is, I'll do some testing post merge just in case there are other problems.

Thanks!

**Comment by FrostyCoolSlug** [comment]
I may end up reverting this, the entire effects section was non-functional..

Respectfully, could you make PRs once the work and changes are complete? Rather than in a progressive state?

I'm always happy to accept good quality code, which you've obviously put the time in here to provide (It's a lot better than what was there previously!), but stuff becomes tricky when I have to start running through it correcting some unfortnunately major issues with it..

The improvements you're making are good, I wouldn't have merged them if they weren't.. I do understand that there's a bit of difficulty spending time making changes that could be rejected, but I promise you, for this level of change, I'll always be open to completed PRs, 

I'll happily admit that the original code was, and is, a mess that needs improvements which you've clearly provided here, but preemptive PRs make it a little difficult to determine what's complete and what's not, which can leave things in an unfortunate state when I accept the merge, and various things are broken!

Thanks.

**Comment by donutcrab** [comment]
I'm sorry for the inconvenience the pr caused.
I only own the goxlr mini and couldn't test the sampler and effects tabs properly.

Since last week my schedule is quite tight again, so I don't have time to continue refactoring at the moment.
I hope the fixes weren't too time consuming for you.

**Comment by FrostyCoolSlug** [comment]
Thanks for the work you've done. While it was a bit of a problem initially, I kept the code in because it was well developed, and after making a few tweaks and changes to bring it inline with the rest of the code, I've been migrating everything across to your new containers, and deprecating the old ones. 

A lot of the code, especially with the containers and `ListSelection` has become a *LOT* cleaner thanks to your efforts!

Thanks again.

**Pull request merged**
