### PR TITLE
Feature: Add scroll wheel support to visualiser

### PR DESCRIPTION
**Pull request by NinjaLabs-Dev**
## Summary
Allows the user to scroll up & down while hovering over a fader on the visualiser.

Requested from Issue #1 

Example of Usage can be seen [here on Imgur](https://i.imgur.com/sdureLr.mp4)

### CODE REVIEW

**Comment by NinjaLabs-Dev** [comment]
I've also extended this support to the regular volume sliders throughout the app.

One issue I came across was limiting the sliders dynamically for the visualiser, unlike the sliders a max value isn't defined (as expected) so I've had to put in some hard-coded values to stop the slider from going past the top & bottom of the slider.

This code snippet is form FaderGroup.vue, line 84-88
```js
if(newValue > 250) {
  newValue = 250;
} else if(newValue < 0) {
  newValue = 0;
}
```

Any suggestions on how this could be "cleaner" would be appreciated.

**Comment by FrostyCoolSlug** [comment]
Hi there, thanks for the PR I'm going to need to hold on merging this one temporarily, #23 replaces the existing visualisation with a full SVG replacement, which I'm hoping to merge in first, so this may need to be refactored to accommodate. I'll follow up again once that's done.

**Comment by NinjaLabs-Dev** [comment]
Sounds like a plan

**Comment by NinjaLabs-Dev** [comment]
Merge conflicts resolved and updated code to support the new SVG design (looks great btw)

**Comment by FrostyCoolSlug** [comment]
Looks good, I'll merge it in.

**Pull request merged**
